export enum Department {
    PRODUCTION_AND_OPERATIONS = 'PRODUCTION AND OPERATIONS',
    RESEARCH_AND_DEVELOPMENT = 'RESEARCH_AND_DEVELOPMENT',
    PURCHASING = 'PURCHASING',
    MARKETING = 'MARKETING',
    HUMAN_RESOURCES = 'HUMAN RESOURCES',
    ACCOUNTING_AND_FINANCE = 'ACCOUNTING AND FINANCE'
}
